apiVersion: v1
kind: ServiceAccount
metadata:
  name: db
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  containers:
  - name: db
    image: codydearkland/cmbu-db-app:latest
    ports:
    - containerPort: 5432
  serviceAccountName: db
---
apiVersion: v1
kind: Pod
metadata:
  name: api
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-upstreams": "db:5432:eks,app-frontend:80:vsphere"
    "vault.hashicorp.com/agent-inject": "true"
    "vault.hashicorp.com/agent-inject-secret-db": "secret/db"
    "vault.hashicorp.com/role": "api"
    "vault.hashicorp.com/agent-inject-template-db": |
          {{- with secret "secret/db" -}}
          host=localhost port=5432 dbname=posts user={{ .Data.username }} password={{ .Data.password  }}
          {{- end }}
spec:
  containers:
  - name: api
    image: codydearkland/app-backend:latest
    env:
    - name: POSTGRES_HOST
      value: "localhost"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres_password"
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_DATABASE
      value: "posts"
    ports:
    - containerPort: 5000
  serviceAccountName: api
