apiVersion: v1
kind: Pod
metadata:
  name: db
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
  namespace: custom-application
spec:
  containers:
  - name: db
    image: codydearkland/cmbu-db-app:latest
    ports:
    - containerPort: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: pyapi
  namespace: custom-application
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-upstreams": "db:5432,app-frontend:80"

spec:
  containers:
  - name: pyapi
    image: codydearkland/app-backend:latest
    env:
    - name: POSTGRES_HOST
      value: "localhost"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres_password"
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_DATABASE
      value: "posts" 
    ports:
    - containerPort: 5000
