apiVersion: v1
kind: Namespace
metadata:
  name: custom-application
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
  namespace: custom-application
spec:
  containers:
  - name: db
    image: codydearkland/cmbu-db-app:latest
    ports:
    - containerPort: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: pyapi
  namespace: custom-application
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/service-meta-version": "v2"
    "consul.hashicorp.com/connect-service-port": "http"
    "consul.hashicorp.com/connect-service-upstreams": "db:5432,app-frontend:80"

spec:
  containers:
  - name: pyapi
    image: codydearkland/app-backend:latest
    env:
    - name: POSTGRES_HOST
      value: "localhost"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres_password"
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_DATABASE
      value: "posts"
    ports:
    - containerPort: 5000
      name: http
---
apiVersion: v1
kind: Pod
metadata:
  name: app-frontend
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-port": "80"
    "consul.hashicorp.com/connect-service-upstreams": "pyapi:5000"
    "consul.hashicorp.com/service-meta-version": "v2"
  namespace: custom-application
  labels:
    app: bootcamp
spec:
  containers:
  - name: frontend
    image: codydearkland/app-frontend:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: custom-application
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bootcamp
  type: LoadBalancer