---
apiVersion: v1
kind: Pod
metadata:
  name: app-frontend-dark
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-port": "http"
    "consul.hashicorp.com/connect-service-upstreams": "pyapi:5000"
  namespace: custom-application
  labels:
    app: hashi-demo
spec:
  containers:
  - name: frontend-v2
    image: codydearkland/app-frontend-dark:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: custom-application
  name: frontend-v2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hashi-demo
  type: LoadBalancer
